#!/bin/bash
dockeruser=${DOCKERUSER}
dockerpass=${DOCKERPASS}
docker login --username="$dockeruser" --password="$dockerpass"
if [ -z $1 ];
then
	echo "No repository name given as parameter."
else
	repo=$(echo $1 | cut -d':' -f1)
	if [[ $1 == *":"* ]]; then
		tag=$(echo $1 | cut -d':' -f2)
	else
		tag="latest"
	fi
	if [ -z $2 ]; then
		docker images | grep "$repo" | awk '{print $1":"$2}' | xargs docker rmi
	else
		if [[ $2 != "leave-images" ]]; then
			docker images | grep "$repo" | awk '{print $1":"$2}' | xargs docker rmi
		else
			echo "leaving local images intact."
		fi
	fi
	echo "building $repo:$tag"
	docker build -t "$repo:$tag" .
	docker build -t "$dockeruser/$repo:$tag" .
	docker push "$dockeruser/$repo:$tag"
	docker run 	--name="dockerhub-description" \
			-v $PWD:/workspace \
			-e DOCKERHUB_USERNAME="$dockeruser" \
			-e DOCKERHUB_PASSWORD="$dockerpass" \
			-e DOCKERHUB_REPOSITORY="$dockeruser/$repo" \
			-e README_FILEPATH='/workspace/README.md' \
			peterevans/dockerhub-description:latest
	docker rm dockerhub-description
fi
