#!/bin/bash
CF="/mnt/github/credentials.txt"
source "$CF"
dockeruser=${DOCKERUSER}
dockerpass=${DOCKERPASS}
docker login --username="$dockeruser" --password="$dockerpass"
if [ -z $1 ];
then
	echo "No repository name given as parameter."
	exit 0
else
	repo=$(echo $1 | cut -d':' -f1)
	if [[ $1 == *":"* ]]; then
		tag=$(echo $1 | cut -d':' -f2)
	else
		tag="latest"
	fi
	if [ -z $2 ]; then
		echo "leaving local images intact. use --purge-images as parameter 2 to remove them."
	else
		if [[ $2 == "--purge-images" ]]; then
			docker images | grep "$repo" | awk '{print $1":"$2}' | xargs docker rmi
		else
			echo "leaving local images intact. use --purge-images as parameter 2 to remove them."
		fi
	fi
	echo " (1/4) building $repo:$tag"
	docker build -t "$repo:$tag" .
	echo " (2/4) building $repo:$tag"
	docker build -t "$dockeruser/$repo:$tag" .
	echo " (3/4) building $repo:$tag"
	docker push "$dockeruser/$repo:$tag"
	echo " (4/4) building $repo:$tag"
	docker run 	--name="dockerhub-description" \
			-v $PWD:/workspace \
			-e DOCKERHUB_USERNAME="$dockeruser" \
			-e DOCKERHUB_PASSWORD="$dockerpass" \
			-e DOCKERHUB_REPOSITORY="$dockeruser/$repo" \
			-e README_FILEPATH='/workspace/README.md' \
			peterevans/dockerhub-description:latest
	docker rm dockerhub-description
fi
