#!/bin/bash
CF="/mnt/github/.credentials.txt"
source "$CF"

if [ -z "$GITUSER" ]; then
	echo "Variable GITUSER is not set. Use the command"
	echo " export GITUSER=yourgituseraccount"
	echo "to set it."
	exit 0
fi
if [ -z "$GITMAIL" ]; then
	echo "Variable GITMAIL is not set. Use the command"
	echo " export GITMAIL=yourgitmail"
	echo "to set it."
	exit 0
fi
/usr/bin/git config --global user.name "$GITUSER"
/usr/bin/git config --global user.email "$GITMAIL"
if [ -z "$1" ]; then
	comment="no comment"
else
	if [[ $1 == "--help" || $1 == "-h" ]]; then
		echo "gitpush usage:"
		echo "gitpush [comment] [build]"
		echo "  default comment = \"no comment\""
		echo "  default build = \"main\""
		exit 0
	else
		comment="$1"
	fi
fi
if [ -z "$2" ]; then 
	build="main"
else
	build="$2"
	git checkout -b $2 2>/dev/null
fi
currentdir=${PWD##*/}
echo "repository = $currentdir"
echo ">git branch -r"
git branch -r
echo ">git remote set-url origin \"$GITROOT/$GITREPOUSER/$currentdir.git\""
git remote set-url origin "$GITROOT/$GITREPOUSER/$currentdir.git"
echo ">git remote show origin"
git remote show origin
echo ">git checkout $build"
git checkout $build
echo ">git status"
git status
echo ">git add *"
git add * 2>/dev/null
echo ">git commit -a -m \"$comment\""
git commit -a -m "$comment"
echo ">git push -u origin $build"
git push -u origin $build

